channels:
- conda-forge
dependencies:
- python=3.8.10
- pip
- pip:
  - mlflow
  - cffi==1.15.0
  - cloudpickle==2.0.0
  - defusedxml==0.7.1
  - lightgbm==3.3.0
  - matplotlib==3.4.3
  - scikit-learn==0.23.2
name: mlflow-env
